### ISSUE TITLE
Error when updating connection string

### ISSUE THREAD

**Issue by proanalyticsdev** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#40]
I'm using the sample application to import a PBIX desktop file into an existing workspace. The import works fine but when I try to update the connection string, I get an error:
Ooops, something broke: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
at Microsoft.PowerBI.Api.V1.Gateways.<PatchDatasourceWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.PowerBI.Api.V1.GatewaysExtensions.<PatchDatasourceAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at ProvisionSample.Program.<UpdateConnection>d__28.MoveNext() in C:\Projects\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs:line 625
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at ProvisionSample.Program.<Run>d__18.MoveNext() in C:\Projects\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs:line 240

Any idea what might be the problem?

**Comment by sheggem** [comment]
I also have the same issue. codeline : await client.Gateways.PatchDatasourceAsync(workspaceCollectionName, workspaceId, gatewayId, datasourceId, delta);
Database is Azure SQL

**Comment by johnanish** [comment]
getting the exact same error as mentioned. not sure why this is happening though.

**Comment by cruise-insights** [comment]
I am getting the same issue, it was working previously but has stopped now
Please Suggest some way to change credentials

![image](https://cloud.githubusercontent.com/assets/7963522/21740535/5b78e506-d4e2-11e6-9f0d-b9cae0c4466b.png)

**Comment by kiss96803** [comment]
I have get the same issues,Please Notify that error code has two result , one is 'BadRequest' And the other is  'NotFound'

**Comment by cruise-insights** [comment]
Hi, you can use the PowerBI Cli 1.0.4 available in NPM for Provisioning (Including Update-Connection) , it works.

In .NET the SetAllConnectionAsync Call fails with Bad Request, I assume the API and Parameter Definition/Usage has changed in the .NET SDK

**Comment by kiss96803** [comment]
@cruise-insights  Thanks a lot, It really works. I have the same opinion with you ,There are some conflicts in sdk and the Introduction to the official website need to update。

**Comment by cruise-insights** [comment]
@magnusjohannesson , @johnanish , @sheggem , @paulbatum 

Did the error resolve?

**Comment by proanalyticsdev** [comment]
Yes, it was a Microsoft issue and they have corrected it.
